name: Copy files to Strattic

on:
  push:
    branches:
      - dev
  release:
    types: [published]

env:
  dest_path: '/public_html/wp-content/plugins/centre-remove-absolute-urls'

jobs:
  rclone-dev:
    runs-on: ubuntu-latest
    if: ${{ (github.event.release.target_commitish || github.ref_name) == 'dev' }}

    steps:
      - uses: actions/checkout@v2

      - name: Copy convert paths plugin files on dev
        uses: wei/rclone@v1
        env:
          RCLONE_CONFIG_HDX_TYPE: ${{ secrets.RCLONE_CONFIG_HDX_TYPE }}
          RCLONE_CONFIG_HDX_HOST: ${{ secrets.RCLONE_CONFIG_HDX_HOST }}
          RCLONE_CONFIG_HDX_USER: ${{ secrets.RCLONE_CONFIG_HDX_USER_DEV }}
          RCLONE_CONFIG_HDX_PASS: ${{ secrets.RCLONE_CONFIG_HDX_PASS_DEV }}
        with:
          args: copy convert-absolute-to-relative-urls HDX:/public_html/wp-content/plugins/

      - name: Copy disable things plugin files on dev
        uses: wei/rclone@v1
        env:
          RCLONE_CONFIG_HDX_TYPE: ${{ secrets.RCLONE_CONFIG_HDX_TYPE }}
          RCLONE_CONFIG_HDX_HOST: ${{ secrets.RCLONE_CONFIG_HDX_HOST }}
          RCLONE_CONFIG_HDX_USER: ${{ secrets.RCLONE_CONFIG_HDX_USER_DEV }}
          RCLONE_CONFIG_HDX_PASS: ${{ secrets.RCLONE_CONFIG_HDX_PASS_DEV }}
        with:
          args: copy disable-things HDX:/public_html/wp-content/plugins/

  rclone-prod:
    runs-on: ubuntu-latest
    if: ${{ (github.event.release.target_commitish || github.ref_name) == 'main' }}

    steps:
      - uses: actions/checkout@v2

      - name: Copy convert paths plugin files on prod
        uses: wei/rclone@v1
        env:
          RCLONE_CONFIG_HDX_TYPE: ${{ secrets.RCLONE_CONFIG_HDX_TYPE }}
          RCLONE_CONFIG_HDX_HOST: ${{ secrets.RCLONE_CONFIG_HDX_HOST }}
          RCLONE_CONFIG_HDX_USER: ${{ secrets.RCLONE_CONFIG_HDX_USER_PROD }}
          RCLONE_CONFIG_HDX_PASS: ${{ secrets.RCLONE_CONFIG_HDX_PASS_PROD }}
        with:
          args: copy convert-absolute-to-relative-urls HDX:/public_html/wp-content/plugins/

      - name: Copy disable things plugin files on prod
        uses: wei/rclone@v1
        env:
          RCLONE_CONFIG_HDX_TYPE: ${{ secrets.RCLONE_CONFIG_HDX_TYPE }}
          RCLONE_CONFIG_HDX_HOST: ${{ secrets.RCLONE_CONFIG_HDX_HOST }}
          RCLONE_CONFIG_HDX_USER: ${{ secrets.RCLONE_CONFIG_HDX_USER_PROD }}
          RCLONE_CONFIG_HDX_PASS: ${{ secrets.RCLONE_CONFIG_HDX_PASS_PROD }}
        with:
          args: copy disable-things HDX:/public_html/wp-content/plugins/
